import type { Metadata } from "next";
import Link from "next/link";
import { getIdentity, readAccount } from "@/lib/accounts";
import { parseOpportunityQuery } from "@/lib/marketplace/domain";
import { savedOpportunityIds, searchOpportunities } from "@/lib/marketplace/repository";
import { SaveOpportunity } from "@/components/opportunity-actions";
export const metadata: Metadata = { title: "Opportunities", description: "Search jobs, internships, hackathons, challenges, and college programs." };
const types = [["job", "Jobs"], ["internship", "Internships"], ["hackathon", "Hackathons"], ["ngo_challenge", "NGO challenges"], ["college_program", "College programs"]];
export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = parseOpportunityQuery(raw); const identity = await getIdentity(); const profile = identity ? (await readAccount(identity)).profile : null;
  const [results, saved] = await Promise.all([searchOpportunities(query, profile), identity ? savedOpportunityIds(identity) : Promise.resolve([])]);
  const link = (page: number) => { const p = new URLSearchParams(); for (const [key, value] of Object.entries(raw)) for (const item of Array.isArray(value) ? value : value ? [value] : []) p.append(key, item); p.set("page", String(page)); return `?${p}`; };
  return <main id="page-content" className="market-page"><header className="market-hero"><p className="market-kicker">Build your next chapter</p><h1>Find an opportunity worth pursuing</h1><p>Explore verified jobs, internships, challenges, and learning programs.</p></header>
    <form className="market-search" action="/opportunities"><label>Search<input name="q" defaultValue={query.q} placeholder="Title, organization, or skill" /></label><label>Type<select name="type" defaultValue={query.types[0] || ""}><option value="">All types</option>{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Category<input name="category" defaultValue={query.categories[0]} placeholder="e.g. engineering" /></label><label>Skill<input name="skill" defaultValue={query.skills[0]} placeholder="e.g. TypeScript" /></label><label>Location<input name="location" defaultValue={query.location} placeholder="City or country" /></label><label>Work mode<select name="mode" defaultValue={query.modes[0] || ""}><option value="">Any mode</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">Onsite</option></select></label><label>Compensation<select name="compensation" defaultValue={query.compensation}><option value="any">Any</option><option value="paid">Paid</option><option value="unpaid">Unpaid</option></select></label><label>Duration<input name="duration" defaultValue={query.duration} placeholder="e.g. 6 months" /></label><label>Eligibility<select name="eligibility" defaultValue={query.eligibility}><option value="any">Show all</option><option value="eligible">Eligible for me</option></select></label><label>Deadline<select name="deadline" defaultValue={query.deadline}><option value="open">Open</option><option value="upcoming">Closing soon</option><option value="all">All published</option></select></label><div className="market-filter-actions"><button className="market-button" type="submit">Search</button><Link href="/opportunities">Reset filters</Link></div></form>
    <section className="market-results" aria-live="polite"><div className="market-results-heading"><h2>{results.total} {results.total === 1 ? "opportunity" : "opportunities"}</h2><span>Page {results.page} of {results.pages}</span></div>
      {results.items.length ? <div className="market-grid">{results.items.map(opportunity => <article className="market-card" key={opportunity.id}><div><span className="market-badge">{opportunity.type.replaceAll("_", " ")}</span>{opportunity.organization.verified && <span className="market-verified">Verified</span>}</div><h3><Link href={`/opportunities/${opportunity.slug}`}>{opportunity.title}</Link></h3><p className="market-org">{opportunity.organization.name}</p><p>{opportunity.summary}</p><ul><li>{opportunity.workMode} · {opportunity.location}</li>{opportunity.duration && <li>{opportunity.duration}</li>}<li>{opportunity.skills.slice(0, 3).join(" · ")}</li></ul><div className="market-card-actions"><Link className="market-button" href={`/opportunities/${opportunity.slug}`}>View details</Link><SaveOpportunity slug={opportunity.slug} initialSaved={saved.includes(opportunity.id)} signedIn={!!identity} /></div></article>)}</div> : <div className="market-empty"><h2>No opportunities match those filters</h2><p>Try removing a filter or broadening your search.</p><Link href="/opportunities">Reset all filters</Link></div>}
      {results.pages > 1 && <nav className="market-pagination" aria-label="Results pages">{results.page > 1 && <Link href={link(results.page - 1)}>Previous</Link>}<span>Page {results.page} of {results.pages}</span>{results.page < results.pages && <Link href={link(results.page + 1)}>Next</Link>}</nav>}
    </section></main>;
}
