import { afterAll, beforeAll, expect, it } from "vitest";
import { mkdtemp, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { randomUUID } from "node:crypto";
import type { Identity } from "@/lib/identity/authorization";
import * as organizations from "@/lib/events/organizations";
import * as competitions from "@/lib/events/competitions";
import * as assessments from "@/lib/events/assessments";
import { mutate } from "@/lib/events/store";
const owner:Identity={id:randomUUID(),email:"owner@example.com"}, reviewer:Identity={id:randomUUID(),email:"admin@example.com"}, learner:Identity={id:randomUUID(),email:"learner@example.com"}, teammate:Identity={id:randomUUID(),email:"teammate@example.com"}, judge:Identity={id:randomUUID(),email:"judge@example.com"}, outsider:Identity={id:randomUUID(),email:"outsider@example.com"};
let directory:string;
const at=(offset:number)=>new Date(Date.now()+offset).toISOString();
beforeAll(async()=>{directory=await mkdtemp(path.join(os.tmpdir(),"buildora-events-"));process.env.BUILDORA_LOCAL_DATA_DIR=directory;process.env.BUILDORA_REVIEWER_EMAILS=reviewer.email;});
afterAll(async()=>{await rm(directory,{recursive:true,force:true});delete process.env.BUILDORA_LOCAL_DATA_DIR;delete process.env.BUILDORA_REVIEWER_EMAILS;});
it("enforces membership, review, event, judging, and timed attempt lifecycle",async()=>{
  const org=await organizations.createOrganization(owner,{legalName:"Acme Legal",name:"Acme",type:"organizer",country:"IN",jurisdiction:"Karnataka"});
  await expect(organizations.privateOrganization(outsider,org.id)).rejects.toMatchObject({status:403});
  const invite=await organizations.invite(owner,org.id,judge.email,"evaluator");
  await expect(organizations.acceptInvitation(outsider,invite.token!)).rejects.toMatchObject({status:404});
  expect(await organizations.acceptInvitation(judge,invite.token!)).toBe(org.id);
  expect(await organizations.acceptInvitation(judge,invite.token!)).toBe(org.id);
  await expect(organizations.changeRole(owner,org.id,(await organizations.privateOrganization(owner,org.id)).members.find(x=>x.role==="owner")!.id,"viewer")).rejects.toMatchObject({status:400});
  const questionId=randomUUID(), optionA=randomUUID(),optionB=randomUUID();
  const input={title:"Autumn Hack",description:"Build something useful",format:"online" as const,registrationOpensAt:at(-60000),registrationClosesAt:at(3600000),startsAt:at(-60000),endsAt:at(7200000),teamDeadline:at(3600000),submissionDeadline:at(3600000),capacity:2,minTeamSize:1,maxTeamSize:2,problemStatements:["Civic tech"],prizes:["Prize"],faqs:[],resources:[],rounds:[],criteria:[{id:randomUUID(),name:"Impact",max:10}]};
  await expect(competitions.createCompetition(owner,org.id,input)).rejects.toMatchObject({status:403});
  await organizations.addEvidence(owner,org.id,{category:"legal_identity",filename:"company.pdf",mimeType:"application/pdf",contentBase64:Buffer.from("%PDF-1.7\nexample").toString("base64")});
  const submitted=await organizations.submitVerification(owner,org.id);
  await expect(organizations.reviewVerification(outsider,submitted.id,"approved")).rejects.toMatchObject({status:403});
  await organizations.reviewVerification(reviewer,submitted.id,"approved");
  const c=await competitions.createCompetition(owner,org.id,input);
  await expect(competitions.publishCompetition(outsider,c.id)).rejects.toMatchObject({status:403});
  await competitions.publishCompetition(owner,c.id);
  expect((await competitions.publicCompetition(c.slug))?.organization.verified).toBe(true);
  const registration=await competitions.register(learner,c.id);expect((await competitions.register(learner,c.id)).id).toBe(registration.id);
  await competitions.register(teammate,c.id);
  await expect(competitions.register(outsider,c.id)).rejects.toMatchObject({status:409});
  const team=await competitions.createTeam(learner,c.id,"Team One");
  const teamInvite=await competitions.inviteTeam(learner,team.id,teammate.email);
  await expect(competitions.joinTeam(outsider,teamInvite.token)).rejects.toMatchObject({status:404});
  expect((await competitions.joinTeam(teammate,teamInvite.token)).members).toContain(teammate.id);
  expect((await competitions.joinTeam(teammate,teamInvite.token)).members).toHaveLength(2);
  const submission=await competitions.submitProject(learner,team.id,{problemIndex:0,name:"Solution",description:"A useful app"});
  expect((await competitions.submitProject(learner,team.id,{problemIndex:0,name:"Different",description:"Retry"})).id).toBe(submission.id);
  await expect(competitions.score(outsider,submission.id,input.criteria[0].id,9,"",true)).rejects.toMatchObject({status:403});
  await competitions.assignJudge(owner,submission.id,judge.id);
  await competitions.score(judge,submission.id,input.criteria[0].id,9,"Good",true);
  await expect(competitions.score(judge,submission.id,input.criteria[0].id,8,"Changed",true)).rejects.toMatchObject({status:409});
  await mutate(s=>{s.competitions.find(x=>x.id===c.id)!.submissionDeadline=at(-1000);});
  await expect(competitions.submitProject(learner,randomUUID(),{problemIndex:0,name:"Late",description:"Late"})).rejects.toMatchObject({status:404});
  expect((await competitions.publishResults(owner,c.id))[0].total).toBe(9);
  const a=await assessments.createAssessment(owner,c.id,{title:"Quiz",instructions:"Choose",disclosure:"We record tab focus changes for manual review.",durationSeconds:60,maxAttempts:1,opensAt:at(-1000),closesAt:at(3600000),questions:[{id:questionId,prompt:"Pick A",type:"single",options:[{id:optionA,text:"A"},{id:optionB,text:"B"}],correct:[optionA],points:5}]});
  await assessments.publishAssessment(owner,a.id);
  await expect(assessments.startAttempt(learner,a.id,false)).rejects.toMatchObject({status:400});
  const attempt=await assessments.startAttempt(learner,a.id,true);expect(JSON.stringify(attempt)).not.toContain('"correct"');
  expect((await assessments.startAttempt(learner,a.id,true)).id).toBe(attempt.id);
  await expect(assessments.getAttempt(outsider,attempt.id)).rejects.toMatchObject({status:404});
  await expect(assessments.saveAnswers(learner,attempt.id,{[questionId]:[randomUUID()]})).rejects.toMatchObject({status:400});
  await assessments.saveAnswers(learner,attempt.id,{[questionId]:[optionA]});
  expect((await assessments.getAttempt(learner,attempt.id)).answers[questionId]).toEqual([optionA]);
  const result=await assessments.submitAttempt(learner,attempt.id);expect(result.score).toBe(5);expect((await assessments.submitAttempt(learner,attempt.id)).reference).toBe(result.reference);
  await expect(assessments.saveAnswers(learner,attempt.id,{[questionId]:[optionB]})).rejects.toMatchObject({status:409});
  await expect(assessments.startAttempt(learner,a.id,true)).rejects.toMatchObject({status:409});
  const expiryQuestion=randomUUID(),expiryOption=randomUUID();
  const expiredAssessment=await assessments.createAssessment(owner,c.id,{title:"Expiry",instructions:"Choose",disclosure:"Start time is recorded.",durationSeconds:30,maxAttempts:1,opensAt:at(-1000),closesAt:at(3600000),questions:[{id:expiryQuestion,prompt:"Pick",type:"single",options:[{id:expiryOption,text:"One"},{id:randomUUID(),text:"Two"}],correct:[expiryOption],points:1}]});
  await assessments.publishAssessment(owner,expiredAssessment.id);
  const expiring=await assessments.startAttempt(learner,expiredAssessment.id,true);
  await mutate(s=>{s.attempts.find(x=>x.id===expiring.id)!.expiresAt=at(-1000)});
  expect((await assessments.getAttempt(learner,expiring.id)).state).toBe("expired");
  await expect(assessments.saveAnswers(learner,expiring.id,{[expiryQuestion]:[expiryOption]})).rejects.toMatchObject({status:409});
  await organizations.updateOrganization(owner,org.id,{website:"https://new.example.com"});
  expect(await competitions.publicCompetition(c.slug)).toBeNull();
  await expect(competitions.register(outsider,c.id)).rejects.toMatchObject({status:400});
});
