import { PGlite } from "@electric-sql/pglite";
import { readFile } from "node:fs/promises";
import { afterAll, beforeAll, expect, it } from "vitest";
const db = new PGlite(); const learner = "00000000-0000-4000-8000-000000000011"; const other = "00000000-0000-4000-8000-000000000012"; const employer = "00000000-0000-4000-8000-000000000013";
async function asUser(id: string, sql: string) { await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${id}',false)`); try { return await db.query(sql); } finally { await db.exec("reset role"); } }
beforeAll(async () => { await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}'); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated; insert into auth.users(id,email) values('${learner}','learner@example.com'),('${other}','other@example.com'),('${employer}','employer@example.com');`); await db.exec(await readFile("supabase/migrations/202610020001_identity.sql", "utf8")); await db.exec(await readFile("supabase/migrations/202610020002_marketplace_applications.sql", "utf8")); await db.exec(`insert into public.organizations(id,slug,name,verified) values('30000000-0000-4000-8000-000000000001','org','Org',true); insert into public.organization_memberships(organization_id,user_id,role) values('30000000-0000-4000-8000-000000000001','${employer}','recruiter'); insert into public.opportunities(id,organization_id,slug,title,type,status,deadline) values('20000000-0000-4000-8000-000000000001','30000000-0000-4000-8000-000000000001','job','Job','job','published','2027-12-31'); insert into public.application_questions(opportunity_id,id,label,type,required) values('20000000-0000-4000-8000-000000000001','why','Why?','text',true);`); }, 30000);
afterAll(async () => db.close());
it("shows only published opportunities anonymously", async () => { await db.exec("set role anon"); try { expect((await db.query("select * from public.opportunities")).rows).toHaveLength(1); } finally { await db.exec("reset role"); } });
it("deduplicates submits and keeps applications owner scoped", async () => { const sql = `select public.save_application('20000000-0000-4000-8000-000000000001','{"why":"Because"}',true,'{}')`; const first = await asUser(learner, sql); const second = await asUser(learner, sql); expect(first.rows).toEqual(second.rows); expect((await asUser(other, "select * from public.applications")).rows).toHaveLength(0); });
it("hides employer notes from learners and other organizations", async () => { const app = (await db.query<{id:string}>("select id from public.applications")).rows[0]; await asUser(employer, `select public.add_employer_note('${app.id}','private')`); await expect(asUser(learner, "select * from public.employer_notes")).rejects.toThrow(); await expect(asUser(other, `select public.employer_applications('job',null)`)).rejects.toThrow("access denied"); });
it("records authorized status changes in history", async () => { const app = (await db.query<{id:string}>("select id from public.applications")).rows[0]; await asUser(employer, `select public.update_application_status('${app.id}','reviewing',null)`); expect((await db.query("select * from public.application_status_history where new_status='reviewing'")).rows).toHaveLength(1); await expect(asUser(other, `select public.update_application_status('${app.id}','accepted',null)`)).rejects.toThrow("access denied"); });
