import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getIdentity, readAccount } from "@/lib/accounts";
import { deadlineState, evaluateEligibility } from "@/lib/marketplace/domain";
import { getOpportunity, listMyApplications, savedOpportunityIds } from "@/lib/marketplace/repository";
import { SaveOpportunity } from "@/components/opportunity-actions";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const opportunity = await getOpportunity((await params).slug); if (!opportunity) return {}; return { title: opportunity.title, description: opportunity.summary, alternates: { canonical: `/opportunities/${opportunity.slug}` } }; }
function date(value?: string) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not specified"; }
export default async function OpportunityPage({ params }: Props) {
  const opportunity = await getOpportunity((await params).slug); if (!opportunity) notFound(); const identity = await getIdentity(); const account = identity ? await readAccount(identity) : null; const eligible = account ? evaluateEligibility(opportunity, account.profile) : null;
  const [saved, applications] = await Promise.all([identity ? savedOpportunityIds(identity) : Promise.resolve([]), identity && ["job", "internship"].includes(opportunity.type) ? listMyApplications(identity) : Promise.resolve([])]); const existing = applications.find(a => a.opportunityId === opportunity.id);
  const accepting = deadlineState(opportunity) !== "closed";
  return <main id="page-content" className="market-page market-detail"><Link className="market-back" href="/opportunities">← All opportunities</Link><header><div><span className="market-badge">{opportunity.type.replaceAll("_", " ")}</span><h1>{opportunity.title}</h1><p className="market-org">{opportunity.organization.name} {opportunity.organization.verified && <span className="market-verified">Verified organization</span>}</p><p>{opportunity.summary}</p></div><aside><SaveOpportunity slug={opportunity.slug} initialSaved={saved.includes(opportunity.id)} signedIn={!!identity}/>{["job", "internship"].includes(opportunity.type) && (existing ? <Link className="market-button" href={existing.status === "draft" ? `/opportunities/${opportunity.slug}/apply` : `/applications/${existing.id}`}>{existing.status === "draft" ? "Resume application" : "View application"}</Link> : accepting ? <Link className="market-button" href={identity ? `/opportunities/${opportunity.slug}/apply` : `/auth?redirect=${encodeURIComponent(`/opportunities/${opportunity.slug}/apply`)}`}>Apply now</Link> : <span>Applications closed</span>)}</aside></header>
    {eligible && <div className={`market-eligibility ${eligible.eligible ? "is-eligible" : ""}`}><strong>{eligible.eligible ? "Your profile appears eligible" : "Eligibility check"}</strong>{eligible.reasons.map(reason => <p key={reason}>{reason}</p>)}</div>}
    <div className="market-detail-grid"><article><section><h2>Overview</h2><p>{opportunity.description}</p></section><section><h2>Requirements and skills</h2><div className="market-tags">{opportunity.skills.map(skill => <span key={skill}>{skill}</span>)}</div></section>{opportunity.benefits.length > 0 && <section><h2>Benefits</h2><ul>{opportunity.benefits.map(item => <li key={item}>{item}</li>)}</ul></section>}<section><h2>Eligibility</h2><p>{Object.keys(opportunity.eligibility).length ? "Eligibility is evaluated against the published rules and your Buildora profile." : "Open to all learners who meet the application requirements."}</p></section>{opportunity.schedule.length > 0 && <section><h2>Schedule</h2>{opportunity.schedule.map(item => <p key={item.label}><strong>{item.label}:</strong> {date(item.at)}</p>)}</section>}{opportunity.faqs.length > 0 && <section><h2>FAQs</h2>{opportunity.faqs.map(faq => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>}</article><aside className="market-facts"><h2>Opportunity details</h2><dl><dt>Work mode</dt><dd>{opportunity.workMode}</dd><dt>Location</dt><dd>{opportunity.location}</dd><dt>Duration</dt><dd>{opportunity.duration || "Not specified"}</dd><dt>Compensation</dt><dd>{opportunity.compensationMaxMinor ? `${opportunity.currency} ${(opportunity.compensationMinMinor || 0) / 100}–${opportunity.compensationMaxMinor / 100}` : "Not specified"}</dd><dt>Deadline</dt><dd>{date(opportunity.deadline)}</dd><dt>Starts</dt><dd>{date(opportunity.startAt)}</dd><dt>Status</dt><dd>{accepting ? "Open" : "Closed"}</dd></dl></aside></div>
  </main>;
}
