import "server-only";
import { randomInt, randomUUID } from "node:crypto";
import { HttpError } from "@/lib/identity/http";
import type { Identity } from "@/lib/identity/authorization";
import { audit, member, mutate, now, read, type Assessment, type Attempt, type Store } from "./store";
function shuffle<T>(items:T[]) { const a=[...items]; for(let i=a.length-1;i>0;i--){ const j=randomInt(i+1); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function assessment(s:Store,id:string) { const a=s.assessments.find(x=>x.id===id); if(!a) throw new HttpError("Assessment not found.",404); return a; }
function eligible(s:Store,user:Identity,a:Assessment) { const c=s.competitions.find(x=>x.id===a.competitionId); if(!c || c.state==="draft" || !s.registrations.some(r=>r.competitionId===c.id && r.userId===user.id)) throw new HttpError("Assessment is unavailable.",403); }
function safeAttempt(a:Assessment,t:Attempt) { return {id:t.id,assessmentId:t.assessmentId,number:t.number,startedAt:t.startedAt,expiresAt:t.expiresAt,state:t.state,answers:t.answers,score:t.score,submittedAt:t.submittedAt,reference:t.reference,questions:t.questionOrder.map(qid=>{ const q=a.questions.find(x=>x.id===qid)!; return {id:q.id,prompt:q.prompt,type:q.type,points:q.points,options:t.optionOrders[qid].map(oid=>q.options.find(x=>x.id===oid)!) }; })}; }
export async function createAssessment(user:Identity,competitionId:string,input:Omit<Assessment,"id"|"competitionId"|"published"|"createdAt">) { return mutate(s=>{ const c=s.competitions.find(x=>x.id===competitionId); if(!c) throw new HttpError("Competition not found.",404); member(s,user,c.organizationId,["owner","event_manager"]); if(!s.organizations.find(o=>o.id===c.organizationId)?.verified) throw new HttpError("Organization verification required.",403); if(input.durationSeconds<30 || input.durationSeconds>14400 || input.maxAttempts<1 || input.maxAttempts>10 || !input.disclosure.trim() || !input.questions.length || new Set(input.questions.map(q=>q.id)).size!==input.questions.length || Date.parse(input.opensAt)>=Date.parse(input.closesAt)) throw new HttpError("Invalid assessment configuration.",400); for(const q of input.questions){const options=new Set(q.options.map(x=>x.id)); if(options.size!==q.options.length || q.options.length<2 || !q.correct.length || new Set(q.correct).size!==q.correct.length || q.correct.some(x=>!options.has(x)) || q.type==="single" && q.correct.length!==1 || q.points<1) throw new HttpError("Invalid question.",400); } const a={...input,id:randomUUID(),competitionId,published:false,createdAt:now()}; s.assessments.push(a); audit(s,user,"assessment.created",a.id); return {id:a.id}; }); }
export async function publishAssessment(user:Identity,id:string) { return mutate(s=>{ const a=assessment(s,id),c=s.competitions.find(x=>x.id===a.competitionId)!; member(s,user,c.organizationId,["owner","event_manager"]); if(c.state==="draft") throw new HttpError("Publish the competition first.",400); if(!a.published){a.published=true; audit(s,user,"assessment.published",id);} return {id}; }); }
export async function assessmentInfo(user:Identity,id:string) { const s=await read(),a=assessment(s,id); eligible(s,user,a); if(!a.published) throw new HttpError("Assessment is unavailable.",404); return {id:a.id,title:a.title,instructions:a.instructions,disclosure:a.disclosure,durationSeconds:a.durationSeconds,maxAttempts:a.maxAttempts,opensAt:a.opensAt,closesAt:a.closesAt,questionCount:a.questions.length}; }
export async function listAssessments(user:Identity,competitionId:string) { const s=await read(); if(!s.registrations.some(r=>r.competitionId===competitionId && r.userId===user.id)) throw new HttpError("Registration required.",403); return s.assessments.filter(a=>a.competitionId===competitionId && a.published).map(a=>({id:a.id,title:a.title,durationSeconds:a.durationSeconds,opensAt:a.opensAt,closesAt:a.closesAt})); }
export async function startAttempt(user:Identity,id:string,consent:boolean) { if(!consent) throw new HttpError("Read and accept the assessment disclosure.",400); return mutate(s=>{ const a=assessment(s,id); eligible(s,user,a); if(!a.published || Date.now()<Date.parse(a.opensAt) || Date.now()>=Date.parse(a.closesAt)) throw new HttpError("Assessment is closed.",400); const prior=s.attempts.filter(t=>t.assessmentId===id && t.userId===user.id); const active=prior.find(t=>t.state==="active" && Date.parse(t.expiresAt)>Date.now()); if(active) return safeAttempt(a,active); for(const t of prior.filter(t=>t.state==="active")){t.state="expired";t.updatedAt=now();} if(prior.length>=a.maxAttempts) throw new HttpError("Attempt limit reached.",409); const at=now(),expiresAt=new Date(Math.min(Date.parse(at)+a.durationSeconds*1000,Date.parse(a.closesAt))).toISOString(); const t:Attempt={id:randomUUID(),assessmentId:id,userId:user.id,number:prior.length+1,startedAt:at,consentedAt:at,expiresAt,state:"active",questionOrder:shuffle(a.questions.map(q=>q.id)),optionOrders:Object.fromEntries(a.questions.map(q=>[q.id,shuffle(q.options.map(o=>o.id))])),answers:{},updatedAt:at}; s.attempts.push(t); s.integrityEvents.push({id:randomUUID(),attemptId:t.id,userId:user.id,type:"started",at}); audit(s,user,"attempt.started",t.id); return safeAttempt(a,t); }); }
export async function getAttempt(user:Identity,id:string) { const s=await read(),t=s.attempts.find(x=>x.id===id && x.userId===user.id); if(!t) throw new HttpError("Attempt not found.",404); return safeAttempt(assessment(s,t.assessmentId),t.state==="active" && Date.now()>=Date.parse(t.expiresAt)?{...t,state:"expired"}:t); }
export async function saveAnswers(user:Identity,id:string,answers:Record<string,string[]>) { return mutate(s=>{ const t=s.attempts.find(x=>x.id===id && x.userId===user.id); if(!t) throw new HttpError("Attempt not found.",404); if(t.state!=="active" || Date.now()>=Date.parse(t.expiresAt)){ if(t.state==="active"){t.state="expired";t.updatedAt=now();} throw new HttpError("Attempt expired or completed.",409); } const a=assessment(s,t.assessmentId); for(const [qid,selected] of Object.entries(answers)){const q=a.questions.find(x=>x.id===qid && t.questionOrder.includes(qid)); if(!q || selected.length>(q.type==="single"?1:q.options.length) || new Set(selected).size!==selected.length || selected.some(oid=>!t.optionOrders[qid].includes(oid))) throw new HttpError("Invalid answer.",400); t.answers[qid]=selected; } t.updatedAt=now(); return safeAttempt(a,t); }); }
export async function submitAttempt(user:Identity,id:string) { return mutate(s=>{ const t=s.attempts.find(x=>x.id===id && x.userId===user.id); if(!t) throw new HttpError("Attempt not found.",404); const a=assessment(s,t.assessmentId); if(t.state==="submitted") return safeAttempt(a,t); if(t.state!=="active" || Date.now()>=Date.parse(t.expiresAt)){t.state="expired";t.updatedAt=now(); throw new HttpError("Attempt expired.",409);} t.score=a.questions.reduce((sum,q)=>{const correct=[...q.correct].sort().join("|"); const actual=[...(t.answers[q.id]||[])].sort().join("|"); return sum+(correct===actual?q.points:0);},0); t.state="submitted";t.submittedAt=now();t.updatedAt=t.submittedAt;t.reference=`ASM-${randomUUID().slice(0,8).toUpperCase()}`; audit(s,user,"attempt.submitted",t.id); return safeAttempt(a,t); }); }
export async function integrityEvent(user:Identity,id:string,type:"blur"|"focus"|"connection_change") { return mutate(s=>{ const t=s.attempts.find(x=>x.id===id && x.userId===user.id); if(!t) throw new HttpError("Attempt not found.",404); const a=assessment(s,t.assessmentId); if(!a.disclosure || t.state!=="active" || Date.now()>=Date.parse(t.expiresAt)) throw new HttpError("Integrity event unavailable.",400); const e={id:randomUUID(),attemptId:id,userId:user.id,type,at:now()}; s.integrityEvents.push(e); return {ok:true}; }); }
export async function reviewAttempt(user:Identity,id:string) { const s=await read(),t=s.attempts.find(x=>x.id===id); if(!t) throw new HttpError("Attempt not found.",404); const a=assessment(s,t.assessmentId),c=s.competitions.find(x=>x.id===a.competitionId)!; member(s,user,c.organizationId,["owner","event_manager"]); return {id:t.id,state:t.state,startedAt:t.startedAt,expiresAt:t.expiresAt,submittedAt:t.submittedAt,score:t.score,reference:t.reference,integrityEvents:s.integrityEvents.filter(e=>e.attemptId===id)}; }
