import "server-only";
import { randomBytes, randomUUID } from "node:crypto";
import { HttpError } from "@/lib/identity/http";
import type { Identity } from "@/lib/identity/authorization";
import { audit, member, mutate, now, read, type Competition, type Store } from "./store";
const managers = ["owner","event_manager"] as const;
function event(s:Store,id:string) { const c=s.competitions.find(x=>x.id===id); if(!c) throw new HttpError("Competition not found.",404); return c; }
function organizer(s:Store,user:Identity,c:Competition) { member(s,user,c.organizationId,[...managers]); }
function registered(s:Store,user:Identity,c:Competition) { if(!s.registrations.some(r=>r.competitionId===c.id && r.userId===user.id)) throw new HttpError("Registration required.",403); }
function open(end:string) { if(Date.now()>Date.parse(end)) throw new HttpError("The deadline has passed.",400); }
function receipt() { return `BLD-${randomUUID().slice(0,8).toUpperCase()}`; }
export async function listPublicCompetitions() { const s=await read(); return s.competitions.filter(c=>c.state!=="draft" && s.organizations.find(o=>o.id===c.organizationId)?.verified).map(c=>publicView(s,c)); }
function publicView(s:Store,c:Competition) { const o=s.organizations.find(x=>x.id===c.organizationId)!; return {...c, organization:{name:o.name,slug:o.slug,verified:o.verified}, registrationCount:s.registrations.filter(r=>r.competitionId===c.id).length,results:c.state==="results_published"?ranking(s,c.id):undefined}; }
export async function publicCompetition(slug:string) { const s=await read(); const c=s.competitions.find(x=>x.slug===slug && x.state!=="draft" && s.organizations.find(o=>o.id===x.organizationId)?.verified); return c?publicView(s,c):null; }
export async function myCompetitions(user:Identity) { const s=await read(); return s.competitions.filter(c=>s.members.some(m=>m.organizationId===c.organizationId && m.userId===user.id && m.status==="accepted")); }
export async function createCompetition(user:Identity,organizationId:string,input:Omit<Competition,"id"|"organizationId"|"slug"|"state"|"createdAt"|"updatedAt">) { return mutate(s=>{ member(s,user,organizationId,[...managers]); const o=s.organizations.find(x=>x.id===organizationId)!; if(!o.verified) throw new HttpError("Organization verification is required.",403); if(!(Date.parse(input.registrationOpensAt)<Date.parse(input.registrationClosesAt) && Date.parse(input.registrationClosesAt)<=Date.parse(input.endsAt) && Date.parse(input.startsAt)<Date.parse(input.endsAt) && Date.parse(input.teamDeadline)<=Date.parse(input.submissionDeadline) && Date.parse(input.submissionDeadline)<=Date.parse(input.endsAt))) throw new HttpError("Invalid event schedule.",400); if(input.minTeamSize<1 || input.maxTeamSize<input.minTeamSize || input.maxTeamSize>20 || input.capacity<1) throw new HttpError("Invalid capacity or team size.",400); const id=randomUUID(),at=now(); const c:Competition={...input,id,organizationId,slug:`${input.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,60)}-${id.slice(0,8)}`,state:"draft",createdAt:at,updatedAt:at}; s.competitions.push(c); audit(s,user,"competition.created",id); return c; }); }
export async function updateCompetition(user:Identity,id:string,changes:Partial<Pick<Competition,"title"|"description"|"location"|"capacity"|"eligibility"|"eligibleRoles"|"problemStatements"|"prizes"|"faqs"|"resources"|"rounds"|"criteria">>) { return mutate(s=>{ const c=event(s,id); organizer(s,user,c); if(c.state!=="draft") throw new HttpError("Published competition settings are locked.",400); Object.assign(c,changes,{updatedAt:now()}); audit(s,user,"competition.updated",id); return c; }); }
export async function publishCompetition(user:Identity,id:string) { return mutate(s=>{ const c=event(s,id); organizer(s,user,c); if(c.state!=="draft" || !s.organizations.find(o=>o.id===c.organizationId)?.verified || !c.criteria.length || c.criteria.some(x=>x.max<=0) || !c.problemStatements.length || Date.parse(c.registrationClosesAt)<=Date.now()) throw new HttpError("Competition is not ready to publish.",400); c.state="published"; c.updatedAt=now(); audit(s,user,"competition.published",id,"draft","published"); return c; }); }
export async function register(user:Identity,id:string,attendance?:"online"|"in-person") { return mutate(s=>{ const c=event(s,id); if(c.state==="draft" || !s.organizations.find(o=>o.id===c.organizationId)?.verified || Date.now()<Date.parse(c.registrationOpensAt)) throw new HttpError("Registration is unavailable.",400); const existing=s.registrations.find(r=>r.competitionId===id && r.userId===user.id); if(existing) return existing; open(c.registrationClosesAt); if(c.eligibleRoles?.length && (!user.localRole || !c.eligibleRoles.includes(user.localRole))) throw new HttpError("Your account is not eligible for this event.",403); if(s.registrations.filter(r=>r.competitionId===id).length>=c.capacity) throw new HttpError("Competition is full.",409); if(c.format==="hybrid" && !attendance) throw new HttpError("Select attendance mode.",400); if(c.format==="online" && attendance==="in-person" || c.format==="in-person" && attendance==="online") throw new HttpError("Invalid attendance mode.",400); const r={id:randomUUID(),competitionId:id,userId:user.id,attendance,at:now(),reference:receipt()}; s.registrations.push(r); audit(s,user,"competition.registered",r.id); return r; }); }
export async function createTeam(user:Identity,id:string,name:string) { return mutate(s=>{ const c=event(s,id); registered(s,user,c); open(c.teamDeadline); if(s.teams.some(t=>t.competitionId===id && t.members.includes(user.id))) throw new HttpError("Already on a team.",409); const t={id:randomUUID(),competitionId:id,name,creatorId:user.id,members:[user.id],invites:[],at:now()}; s.teams.push(t); audit(s,user,"team.created",t.id); return t; }); }
export async function inviteTeam(user:Identity,teamId:string,email:string) { return mutate(s=>{ const t=s.teams.find(x=>x.id===teamId); if(!t || !t.members.includes(user.id)) throw new HttpError("Team not found.",404); const c=event(s,t.competitionId); open(c.teamDeadline); if(t.members.length>=c.maxTeamSize) throw new HttpError("Team is full.",409); const existing=t.invites.find(i=>i.email===email.toLowerCase()); if(existing) return existing; const invite={email:email.toLowerCase(),token:randomBytes(32).toString("hex")}; t.invites.push(invite); audit(s,user,"team.invited",t.id); return invite; }); }
export async function joinTeam(user:Identity,token:string) { return mutate(s=>{ const t=s.teams.find(t=>t.invites.some(i=>i.token===token)); if(!t || !t.invites.some(i=>i.token===token && i.email===user.email.toLowerCase())) throw new HttpError("Invitation not found.",404); const c=event(s,t.competitionId); registered(s,user,c); if(t.members.includes(user.id)) return t; open(c.teamDeadline); if(t.members.length>=c.maxTeamSize || s.teams.some(x=>x.competitionId===c.id && x.members.includes(user.id))) throw new HttpError("Cannot join team.",409); t.members.push(user.id); audit(s,user,"team.joined",t.id); return t; }); }
export async function submitProject(user:Identity,teamId:string,input:Pick<import("./store").Submission,"problemIndex"|"name"|"description"|"repositoryUrl"|"demoUrl">) { return mutate(s=>{ const t=s.teams.find(x=>x.id===teamId); if(!t || !t.members.includes(user.id)) throw new HttpError("Team not found.",404); const c=event(s,t.competitionId); const existing=s.submissions.find(x=>x.teamId===teamId); if(existing) return existing; open(c.submissionDeadline); if(t.members.length<c.minTeamSize || t.members.length>c.maxTeamSize || input.problemIndex<0 || input.problemIndex>=c.problemStatements.length) throw new HttpError("Team or problem is invalid.",400); const submission={...input,id:randomUUID(),competitionId:c.id,teamId,at:now(),reference:receipt()}; s.submissions.push(submission); audit(s,user,"submission.finalized",submission.id); return submission; }); }
export async function assignJudge(user:Identity,submissionId:string,judgeId:string) { return mutate(s=>{ const submission=s.submissions.find(x=>x.id===submissionId); if(!submission) throw new HttpError("Submission not found.",404); const c=event(s,submission.competitionId); organizer(s,user,c); member(s,{id:judgeId,email:""},c.organizationId,["evaluator","owner","event_manager"]); if(s.teams.find(x=>x.id===submission.teamId)?.members.includes(judgeId)) throw new HttpError("Judge has a conflict.",400); const existing=s.assignments.find(a=>a.submissionId===submissionId && a.judgeId===judgeId); if(existing) return existing; const a={id:randomUUID(),submissionId,judgeId,at:now()}; s.assignments.push(a); audit(s,user,"judge.assigned",a.id); return a; }); }
export async function score(user:Identity,submissionId:string,criterionId:string,value:number,feedback:string,finalize:boolean) { return mutate(s=>{ const submission=s.submissions.find(x=>x.id===submissionId); if(!submission || !s.assignments.some(a=>a.submissionId===submissionId && a.judgeId===user.id)) throw new HttpError("Submission not assigned.",403); const c=event(s,submission.competitionId); member(s,user,c.organizationId,["evaluator","owner","event_manager"]); if(s.teams.find(t=>t.id===submission.teamId)?.members.includes(user.id)) throw new HttpError("Judge has a conflict.",403); const criterion=c.criteria.find(x=>x.id===criterionId); if(!criterion || value<0 || value>criterion.max) throw new HttpError("Invalid score.",400); const prior=s.scores.find(x=>x.submissionId===submissionId && x.judgeId===user.id && x.criterionId===criterionId); if(prior?.state==="final") { if(finalize && prior.value===value && prior.feedback===feedback) return prior; throw new HttpError("Final score is locked.",409); } if(prior){ prior.value=value; prior.feedback=feedback; prior.state=finalize?"final":"draft"; prior.at=now(); if(finalize) audit(s,user,"score.finalized",prior.id); return prior; } const score={id:randomUUID(),submissionId,judgeId:user.id,criterionId,value,feedback,state:finalize?"final" as const:"draft" as const,at:now()}; s.scores.push(score); audit(s,user,finalize?"score.finalized":"score.saved",score.id); return score; }); }
export function ranking(s:Store,id:string) { return s.submissions.filter(x=>x.competitionId===id).map(x=>({submissionId:x.id,reference:x.reference,name:x.name,total:s.scores.filter(y=>y.submissionId===x.id && y.state==="final").reduce((sum,y)=>sum+y.value,0)})).sort((a,b)=>b.total-a.total || a.reference.localeCompare(b.reference)); }
export async function publishResults(user:Identity,id:string) { return mutate(s=>{ const c=event(s,id); organizer(s,user,c); if(c.state!=="published" || Date.now()<Date.parse(c.submissionDeadline)) throw new HttpError("Results cannot be published yet.",400); const submissions=s.submissions.filter(x=>x.competitionId===id); if(!submissions.length || submissions.some(x=>!s.assignments.some(a=>a.submissionId===x.id))) throw new HttpError("Every submission needs a judge.",400); for(const a of s.assignments.filter(a=>submissions.some(x=>x.id===a.submissionId))) if(c.criteria.some(q=>!s.scores.some(x=>x.submissionId===a.submissionId && x.judgeId===a.judgeId && x.criterionId===q.id && x.state==="final"))) throw new HttpError("Judging is incomplete.",400); c.state="results_published"; c.updatedAt=now(); audit(s,user,"results.published",id); return ranking(s,id); }); }
export async function eventWorkspace(user:Identity,id:string) { const s=await read(); const c=event(s,id); organizer(s,user,c); return {competition:c,registrations:s.registrations.filter(r=>r.competitionId===id),teams:s.teams.filter(t=>t.competitionId===id).map(t=>({id:t.id,competitionId:t.competitionId,name:t.name,creatorId:t.creatorId,members:t.members,at:t.at})),submissions:s.submissions.filter(x=>x.competitionId===id),assignments:s.assignments.filter(a=>s.submissions.some(x=>x.id===a.submissionId && x.competitionId===id)),scores:s.scores.filter(x=>s.submissions.some(y=>y.id===x.submissionId && y.competitionId===id)),ranking:ranking(s,id)}; }
export async function myEventData(user:Identity,id:string) { const s=await read(); const c=event(s,id); registered(s,user,c); return {registration:s.registrations.find(r=>r.competitionId===id && r.userId===user.id),team:s.teams.find(t=>t.competitionId===id && t.members.includes(user.id)),submission:s.submissions.find(x=>x.competitionId===id && s.teams.some(t=>t.id===x.teamId && t.members.includes(user.id))),results:c.state==="results_published"?ranking(s,id):undefined}; }
export async function judgeWorkspace(user:Identity) { const s=await read(); return s.assignments.filter(a=>a.judgeId===user.id).flatMap(a=>{const submission=s.submissions.find(x=>x.id===a.submissionId)!;const c=event(s,submission.competitionId);if(!s.members.some(m=>m.organizationId===c.organizationId && m.userId===user.id && m.status==="accepted" && ["evaluator","owner","event_manager"].includes(m.role)))return [];return [{submission,competition:{id:c.id,title:c.title,criteria:c.criteria},scores:s.scores.filter(x=>x.submissionId===submission.id && x.judgeId===user.id)}];}); }
