import "server-only";
import { randomBytes, randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { HttpError } from "@/lib/identity/http";
import type { Identity } from "@/lib/identity/authorization";
import { admin, audit, member, mutate, now, read, type Organization, type Role } from "./store";

const ownerRoles: Role[] = ["owner"];
const managerRoles: Role[] = ["owner", "event_manager"];
export async function myOrganizations(identity: Identity) { const s = await read(); return s.organizations.filter(o => s.members.some(m => m.organizationId === o.id && m.userId === identity.id && m.status === "accepted")); }
export async function createOrganization(identity: Identity, input: Pick<Organization,"legalName"|"name"|"type"|"country"|"jurisdiction"> & Partial<Pick<Organization,"website"|"description"|"registrationId"|"address">>) {
  if (!identity.email) throw new HttpError("An email address is required.", 400);
  return mutate(s => { const id = randomUUID(), at = now(); const slug = `${input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,60)}-${id.slice(0,8)}`;
    const organization: Organization = { ...input, id, slug, verified: false, createdAt: at, updatedAt: at }; s.organizations.push(organization);
    s.members.push({ id: randomUUID(), organizationId: id, userId: identity.id, email: identity.email.toLowerCase(), role: "owner", status: "accepted", invitedAt: at, acceptedAt: at, updatedAt: at });
    s.verifications.push({ id: randomUUID(), organizationId: id, state: "draft", evidence: [], updatedAt: at }); audit(s, identity, "organization.created", id); return organization;
  });
}
export async function updateOrganization(identity:Identity,id:string,changes:Partial<Pick<Organization,"legalName"|"name"|"country"|"jurisdiction"|"registrationId"|"address"|"website"|"description">>) { return mutate(s=>{member(s,identity,id,ownerRoles);const o=s.organizations.find(x=>x.id===id)!;const sensitive:(keyof typeof changes)[]=["legalName","country","jurisdiction","registrationId","address","website"];const reverify=sensitive.some(key=>changes[key]!==undefined && changes[key]!==o[key]);Object.assign(o,changes,{updatedAt:now()});if(reverify && o.verified){o.verified=false;const v=s.verifications.find(x=>x.organizationId===id)!;const before=v.state;v.state="needs_changes";v.reason="Organization identity or website changed.";v.updatedAt=now();audit(s,identity,"verification.required",v.id,before,v.state,v.reason);}audit(s,identity,"organization.updated",id);return o;}); }
export async function privateOrganization(identity: Identity, id: string) { const s = await read(); member(s, identity, id); return { organization: s.organizations.find(o => o.id === id), members: s.members.filter(m => m.organizationId === id).map(m => ({id:m.id,organizationId:m.organizationId,userId:m.userId,email:m.email,role:m.role,status:m.status,invitedAt:m.invitedAt,acceptedAt:m.acceptedAt,updatedAt:m.updatedAt})), verification: s.verifications.find(v => v.organizationId === id) }; }
export async function invite(identity: Identity, id: string, email: string, role: Role) { return mutate(s => { member(s,identity,id,ownerRoles); const normalized = email.toLowerCase(); if (s.members.some(m => m.organizationId === id && m.email === normalized && m.status === "accepted")) throw new HttpError("Already a member.",400); const existing = s.members.find(m => m.organizationId === id && m.email === normalized && m.status === "invited"); if (existing) return { token: existing.token, id: existing.id }; const token = randomBytes(32).toString("hex"); const at = now(); const m = { id: randomUUID(), organizationId:id, email: normalized, role, status: "invited" as const, token, invitedAt: at, updatedAt: at }; s.members.push(m); audit(s,identity,"member.invited",m.id,undefined,role); return { token, id:m.id }; }); }
export async function acceptInvitation(identity: Identity, token: string) { return mutate(s => { const m = s.members.find(x => x.token === token || (x.status === "accepted" && x.token === token)); if (!m || m.email !== identity.email.toLowerCase()) throw new HttpError("Invitation not found.",404); if (m.status === "accepted") return m.organizationId; m.userId=identity.id; m.status="accepted"; m.acceptedAt=now(); m.updatedAt=m.acceptedAt; audit(s,identity,"member.accepted",m.id); return m.organizationId; }); }
export async function changeRole(identity: Identity,id:string,memberId:string,role:Role) { return mutate(s => { member(s,identity,id,ownerRoles); const target=s.members.find(m=>m.id===memberId && m.organizationId===id && m.status==="accepted"); if(!target) throw new HttpError("Member not found.",404); if(target.role==="owner" && role!=="owner" && s.members.filter(m=>m.organizationId===id && m.status==="accepted" && m.role==="owner").length<=1) throw new HttpError("The last owner cannot be removed.",400); const prior=target.role; target.role=role; target.updatedAt=now(); audit(s,identity,"member.role_changed",target.id,prior,role); return target; }); }
export async function removeMember(identity:Identity,id:string,memberId:string) { return mutate(s => { member(s,identity,id,ownerRoles); const target=s.members.find(m=>m.id===memberId && m.organizationId===id); if(!target) throw new HttpError("Member not found.",404); if(target.role==="owner" && s.members.filter(m=>m.organizationId===id && m.status==="accepted" && m.role==="owner").length<=1) throw new HttpError("The last owner cannot be removed.",400); s.members=s.members.filter(m=>m.id!==memberId); audit(s,identity,"member.removed",memberId); return {ok:true}; }); }
export async function addEvidence(identity:Identity,id:string,input:{category:string; filename:string; mimeType:string; contentBase64:string}) { const s=await read(); member(s,identity,id,managerRoles); const v=s.verifications.find(x=>x.organizationId===id)!; if(!["draft","needs_changes","rejected"].includes(v.state)) throw new HttpError("Evidence cannot be changed during review.",400); if(!/^[\w .()\-]{1,120}$/.test(input.filename) || !["application/pdf","image/png","image/jpeg"].includes(input.mimeType) || !/^[A-Za-z0-9+/]+={0,2}$/.test(input.contentBase64)) throw new HttpError("Invalid evidence file.",400); const bytes=Buffer.from(input.contentBase64,"base64"); if(bytes.length<1 || bytes.length>10_000_000) throw new HttpError("Evidence exceeds the file size limit.",400); const valid=input.mimeType==="application/pdf"?bytes.subarray(0,5).toString()==="%PDF-":input.mimeType==="image/png"?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes.subarray(0,3).equals(Buffer.from([255,216,255])); if(!valid) throw new HttpError("File contents do not match the selected type.",400); const evidenceId=randomUUID(); const relative=`private/${id}/${evidenceId}`; const location=path.join(path.resolve(process.env.BUILDORA_LOCAL_DATA_DIR || ".local-data"),relative); await fs.mkdir(path.dirname(location),{recursive:true}); await fs.writeFile(location,bytes,{flag:"wx",mode:0o600}); return mutate(store=>{member(store,identity,id,managerRoles); const current=store.verifications.find(x=>x.organizationId===id)!; if(!["draft","needs_changes","rejected"].includes(current.state)) throw new HttpError("Evidence cannot be changed during review.",400); const e={id:evidenceId,category:input.category,filename:input.filename,mimeType:input.mimeType,size:bytes.length,storagePath:relative,uploaderId:identity.id,createdAt:now()}; current.evidence.push(e);current.updatedAt=now();audit(store,identity,"verification.evidence_added",current.id);return e;}); }
export async function submitVerification(identity:Identity,id:string) { return mutate(s=>{ member(s,identity,id,managerRoles); const v=s.verifications.find(x=>x.organizationId===id)!; if(!["draft","needs_changes","rejected"].includes(v.state) || !v.evidence.length) throw new HttpError("Verification evidence is required.",400); const before=v.state; v.state="submitted"; v.submittedAt=now(); v.updatedAt=v.submittedAt; audit(s,identity,"verification.submitted",v.id,before,v.state); return v; }); }
export async function reviewQueue(identity:Identity) { admin(identity); const s=await read(); return s.verifications.filter(v=>["submitted","in_review"].includes(v.state)).map(v=>({verification:v,organization:s.organizations.find(o=>o.id===v.organizationId)})); }
export async function reviewVerification(identity:Identity,id:string,decision:"in_review"|"approved"|"rejected"|"needs_changes",reason?:string) { admin(identity); return mutate(s=>{ const v=s.verifications.find(x=>x.id===id); if(!v) throw new HttpError("Case not found.",404); if(s.members.some(m=>m.organizationId===v.organizationId && m.userId===identity.id)) throw new HttpError("An organization member cannot review its own case.",403); if(!(v.state==="submitted" && decision==="in_review" || ["submitted","in_review"].includes(v.state) && decision!=="in_review")) throw new HttpError("Invalid review transition.",400); if(["rejected","needs_changes"].includes(decision) && !reason?.trim()) throw new HttpError("A reason is required.",400); const before=v.state; v.state=decision; v.reviewerId=identity.id; v.reviewedAt=now(); v.updatedAt=v.reviewedAt; v.reason=reason?.trim(); const org=s.organizations.find(o=>o.id===v.organizationId)!; org.verified=decision==="approved"; org.updatedAt=now(); audit(s,identity,"verification.reviewed",v.id,before,decision,v.reason); return v; }); }
export async function publicOrganization(slug:string) { const s=await read(); const o=s.organizations.find(x=>x.slug===slug); return o?{slug:o.slug,name:o.name,type:o.type,country:o.country,website:o.website,description:o.description,verified:o.verified}:null; }
