"use client";
import { useCallback, useEffect, useState } from "react";
type Question = { id: string; prompt: string; type: "single" | "multi"; options: { id: string; text: string }[]; points: number };
type Attempt = { id: string; expiresAt: string; state: string; answers: Record<string, string[]>; questions: Question[]; score?: number; reference?: string };
type Info = { id: string; title: string; instructions: string; disclosure: string; durationSeconds: number; maxAttempts: number; questionCount: number };
async function request(body: unknown) { const r = await fetch("/api/assessments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.message || "Request failed"); return d.result as Attempt; }
export function AssessmentRunner({ id }: { id: string }) {
  const [info, setInfo] = useState<Info | null>(null);
  const [attempt, setAttempt] = useState<Attempt | null>(null);
  const [consent, setConsent] = useState(false);
  const [error, setError] = useState("");
  const [remaining, setRemaining] = useState(0);
  const load = useCallback(async () => { try { const r = await fetch(`/api/assessments?id=${encodeURIComponent(id)}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.message); setInfo(d.assessment); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load assessment"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!attempt || attempt.state !== "active") return; const tick = () => setRemaining(Math.max(0, Math.ceil((Date.parse(attempt.expiresAt) - Date.now()) / 1000))); tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, [attempt]);
  useEffect(() => { if (!attempt || attempt.state !== "active" || !consent) return; const visibility = () => { void request({ action: "integrity", id: attempt.id, type: document.hidden ? "blur" : "focus" }).catch(() => undefined); }; const connection = () => { void request({ action: "integrity", id: attempt.id, type: "connection_change" }).catch(() => undefined); }; document.addEventListener("visibilitychange", visibility); window.addEventListener("online", connection); window.addEventListener("offline", connection); return () => { document.removeEventListener("visibilitychange", visibility); window.removeEventListener("online", connection); window.removeEventListener("offline", connection); }; }, [attempt, consent]);
  async function run(body: unknown) { try { setError(""); return await request(body); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); return null; } }
  async function select(question: Question, optionId: string) { if (!attempt) return; const existing = attempt.answers[question.id] || []; const next = question.type === "single" ? [optionId] : existing.includes(optionId) ? existing.filter(x => x !== optionId) : [...existing, optionId]; const previous = attempt; setAttempt({ ...attempt, answers: { ...attempt.answers, [question.id]: next } }); const saved = await run({ action: "save", id: attempt.id, answers: { [question.id]: next } }); if (saved) setAttempt(saved); else setAttempt(previous); }
  return <div className="space-y-6"><h1 className="text-3xl font-bold">{info?.title || "Assessment"}</h1>{info && <section className="space-y-2"><p>{info.instructions}</p><p>Duration: {Math.ceil(info.durationSeconds / 60)} minutes · Maximum attempts: {info.maxAttempts} · Questions: {info.questionCount}</p><p className="rounded border p-3">Integrity disclosure: {info.disclosure}</p><label className="block"><input type="checkbox" checked={consent} disabled={!!attempt} onChange={e => setConsent(e.target.checked)} /> I have read the assessment instructions and disclosure.</label></section>}{!attempt && info && <button disabled={!consent} className="rounded bg-black px-4 py-2 text-white disabled:opacity-50" onClick={() => void (async () => { const a = await run({ action: "start", id, consent: true }); if (a) setAttempt(a); })()}>Start or resume attempt</button>}{attempt && <section className="space-y-5"><p>State: {attempt.state} · Time remaining: {remaining}s</p>{attempt.questions.map(q => <fieldset className="rounded border p-4" key={q.id} disabled={attempt.state !== "active" || remaining <= 0}><legend className="font-semibold">{q.prompt} · {q.points} points</legend>{q.options.map(o => <label className="block" key={o.id}><input type={q.type === "single" ? "radio" : "checkbox"} name={q.id} checked={(attempt.answers[q.id] || []).includes(o.id)} onChange={() => void select(q, o.id)} /> {o.text}</label>)}</fieldset>)}{attempt.state === "active" && <button className="rounded bg-black px-4 py-2 text-white" onClick={() => void (async () => { const result = await run({ action: "submit", id: attempt.id }); if (result) setAttempt(result); })()}>Submit final answers</button>}{attempt.reference && <p role="status">Receipt: {attempt.reference} · Score: {attempt.score}</p>}</section>}{error && <p role="alert">{error}</p>}</div>;
}
