"use client";
import { useState } from "react";
import type { Competition, Organization } from "@/lib/events/store";
type Props={organizations:Organization[];competitions:Competition[]};
async function post(path:string,body:unknown){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||"Request failed");return data.result;}
const date=(hours:number)=>new Date(Date.now()+hours*3600000).toISOString();
export function OrganizerWorkspace({organizations,competitions}:Props){const [orgs,setOrgs]=useState(organizations),[events,setEvents]=useState(competitions),[selected,setSelected]=useState(organizations[0]?.id||""),[message,setMessage]=useState("");const [orgName,setOrgName]=useState(""),[legalName,setLegalName]=useState(""),[country,setCountry]=useState(""),[jurisdiction,setJurisdiction]=useState(""),[type,setType]=useState<Organization["type"]>("organizer");const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[capacity,setCapacity]=useState(100),[problem,setProblem]=useState(""),[criterion,setCriterion]=useState("Impact");
  async function run(fn:()=>Promise<unknown>){try{setMessage("Working…");const result=await fn();setMessage("Saved.");return result}catch(error){setMessage(error instanceof Error?error.message:"Request failed");return null}}
  return <div className="space-y-8 py-6"><p>Organization verification is required before event publishing. All dates use UTC.</p>{message&&<p role="status" className="rounded border p-3">{message}</p>}
    <section className="rounded border p-5 space-y-3"><h2 className="text-xl font-semibold">Create organization</h2><input aria-label="Public organization name" placeholder="Public name" className="w-full border p-2" value={orgName} onChange={e=>setOrgName(e.target.value)}/><input aria-label="Legal name" placeholder="Legal name" className="w-full border p-2" value={legalName} onChange={e=>setLegalName(e.target.value)}/><select aria-label="Organization type" className="w-full border p-2" value={type} onChange={e=>setType(e.target.value as Organization["type"])}>{["organizer","employer","college","NGO","partner"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Country" placeholder="Country" className="w-full border p-2" value={country} onChange={e=>setCountry(e.target.value)}/><input aria-label="Jurisdiction" placeholder="Jurisdiction" className="w-full border p-2" value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}/><button className="rounded bg-black px-4 py-2 text-white" onClick={()=>void run(async()=>{const o=await post("/api/organizations",{action:"create",name:orgName,legalName,type,country,jurisdiction});setOrgs([...orgs,o]);setSelected(o.id);return o})}>Create organization</button></section>
    {orgs.length>0&&<section className="rounded border p-5 space-y-3"><h2 className="text-xl font-semibold">Verification</h2><select aria-label="Select organization" className="w-full border p-2" value={selected} onChange={e=>setSelected(e.target.value)}>{orgs.map(o=><option value={o.id} key={o.id}>{o.name} · {o.verified?"verified":"unverified"}</option>)}</select><p>Upload a legal identity, registration, address, or nonprofit document. Files stay private.</p><input type="file" aria-label="Evidence file" accept="application/pdf,image/png,image/jpeg" id="evidence-file"/><button className="rounded border px-4 py-2" onClick={()=>void run(async()=>{const input=document.getElementById("evidence-file") as HTMLInputElement;const file=input.files?.[0];if(!file)throw new Error("Choose a file.");if(file.size>10_000_000)throw new Error("File exceeds 10 MB.");const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(new Error("Unable to read file."));reader.readAsDataURL(file)});return post("/api/organizations",{action:"evidence",organizationId:selected,category:"legal_identity",filename:file.name,mimeType:file.type,contentBase64})})}>Upload evidence</button><button className="rounded border px-4 py-2" onClick={()=>void run(()=>post("/api/organizations",{action:"submit",organizationId:selected}))}>Submit for review</button></section>}
    {orgs.length>0&&<section className="rounded border p-5 space-y-3"><h2 className="text-xl font-semibold">Create competition draft</h2><input className="w-full border p-2" aria-label="Competition title" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="w-full border p-2" aria-label="Description" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><input className="w-full border p-2" type="number" aria-label="Capacity" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/><input className="w-full border p-2" aria-label="Problem statement" placeholder="Problem statement" value={problem} onChange={e=>setProblem(e.target.value)}/><input className="w-full border p-2" aria-label="Judging criterion" placeholder="Judging criterion" value={criterion} onChange={e=>setCriterion(e.target.value)}/><p>Initial schedule: registration opens now, closes in 24 hours, and project submission closes in 48 hours. Edit the draft through the API before publishing if needed.</p><button className="rounded bg-black px-4 py-2 text-white" onClick={()=>void run(async()=>{const c=await post("/api/competitions",{action:"create",organizationId:selected,title,description,format:"online",registrationOpensAt:date(-1),registrationClosesAt:date(24),startsAt:date(25),endsAt:date(72),teamDeadline:date(36),submissionDeadline:date(48),capacity,minTeamSize:1,maxTeamSize:4,problemStatements:[problem],prizes:[],faqs:[],resources:[],rounds:[],criteria:[{id:crypto.randomUUID(),name:criterion,max:10}]});setEvents([...events,c]);return c})}>Create draft</button></section>}
    <section className="rounded border p-5"><h2 className="text-xl font-semibold">Your competitions</h2><ul className="space-y-3">{events.map(c=><li key={c.id} className="border-b py-3"><strong>{c.title}</strong> · {c.state} · <a className="underline" href={`/hackathons/${c.slug}`}>Public preview</a> · <a className="underline" href={`/organizer/competitions/${c.id}`}>Manage</a>{c.state==="draft"&&<button className="ml-3 rounded border px-3 py-1" onClick={()=>void run(async()=>{const updated=await post("/api/competitions",{action:"publish",id:c.id});setEvents(events.map(x=>x.id===c.id?updated:x));return updated})}>Publish</button>}</li>)}</ul></section>
  </div>}
